###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.8'
services:
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025 #smtp port
            - 8025:8025 #webmail port

    redis:
        image: 'redis:alpine'

    mysql:
        image: mysql:8.0
        working_dir: /application
        volumes:
            - db_data:/application
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db_local
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pwd
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
    #        command: [nginx-debug, '-g', 'daemon off;']

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

volumes:
    db_data:
        driver: local
